resources:
- ticket-service.yaml
- reservation-service.yaml
- event-service.yaml
- gateway.yaml
- internal-gateway.yaml
configMapGenerator:
- name: client.properties
  files:
  - appConfig/client.properties 
