apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-deployment
  labels:
    app: event-service 
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: event-service 
    spec:
      containers:
        - name: event-service
          image: asia-east1-docker.pkg.dev/ticket-master-tall15421542/ticket-master/service:v0.0.24
          env:
            - name: CONTAINER_NAME
              value: "asia-east1-docker.pkg.dev/ticket-master-tall15421542/ticket-master/service:v0.0.24"
          command: ["java", "-javaagent:/opentelemetry-javaagent.jar", "-cp", "app.jar"]
          resources:
            requests:
              memory: "4G"
              cpu: "4000m"

